language: node_js
node_js:
  - "4.2.2"
install:
  - npm install
  - npm install -g istanbul
  - npm install -g mocha
script: npm test
service_name: travis-pro
repo_token: etiLDkKPs8KxI4pNMigsPz4ZEEUoTtSSL

#services:
#  - mongodb
#env:
#  - LAIKA_OPTIONS="-t 5000"
